version: '3.8'

services:
  semgrep-scanner:
    build: .
    image: semgrep-custom:latest
    container_name: semgrep-scanner
    volumes:
      # Mount current directory to access output files
      - .:/workspace
      # Mount custom rules (optional, already copied in image)
      - ./custom-semgrep-rules:/app/custom-semgrep-rules:ro
    working_dir: /workspace
    environment:
      - SEMGREP_VERSION=${SEMGREP_VERSION:-latest}
      - WEBSERVER_URL=${WEBSERVER_URL:-http://webserver.local/api/results}
      - API_KEY=${API_KEY:-}
      - COMMIT_SHA=${COMMIT_SHA:-abc123}
      - REPOSITORY_URL=${REPOSITORY_URL:-https://github.com/user/repo.git}
    # Example usage (uncomment to run automatically)
    # command: ["abc123", "https://github.com/user/repo.git", "--api-key", "${API_KEY}"]
    # Or run interactively with: docker-compose run --rm semgrep-scanner
    # Or run with webserver integration: API_KEY=your-key docker-compose run --rm semgrep-scanner
